import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {roboto} from "@/app/ui/font";
import "./globals.css";
import Header from "@/app/ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{color: 'black'}} className={`${roboto.className} bg-wall antialiased`}>
      {children}
      </body>
    </html>
  );
}
